name       : python-pyqt6-sip
version    : 13.3.1
release    : 3
source     :
    - https://pypi.python.org/packages/source/P/PyQt6-sip/PyQt6_sip-13.3.1.tar.gz : d629c0e39d5ccfdae567b92ba74d92f9180b7c55535f82251f1a12a9076a9e01
license    : GPL-3.0-or-later
component  : programming.python
summary    : The sip module support for PyQt6
description: |
    The sip extension module provides support for the PyQt6 package.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
