name       : python-pyqt6-sip
version    : 13.4.0
release    : 5
source     :
    - https://pypi.python.org/packages/source/P/PyQt6-sip/PyQt6_sip-13.4.0.tar.gz : 6d87a3ee5872d7511b76957d68a32109352caf3b7a42a01d9ee20032b350d979
license    : GPL-3.0-or-later
component  : programming.python
summary    : The sip module support for PyQt6
description: |
    The sip extension module provides support for the PyQt6 package.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
